name: CI test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  typecheck:
    runs-on: ubuntu-22.04

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Source branch checkout
      uses: actions/checkout@v2

    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version 1.3.1
        echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc

    - name: Install poetry project
      run: poetry -vvv install --only dev

    - name: Run mypy
      run: poetry run mypy .
